// Copyright 2025 cormoran707
// SPDX-License-Identifier: GPL-2.0-or-later

#define SERIAL_PIO_USE_PIO1
#define WS2812_DI_PIN GP15

#define BOOTMAGIC_ROW_RIGHT 6
#define BOOTMAGIC_COLUMN_RIGHT 6

#define RGBLIGHT_LAYERS

#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_CS_PIN NO_PIN
#define POINTING_DEVICE_SCLK_PIN GP1
#define POINTING_DEVICE_SDIO_PIN GP0
// Not supported for split keyboard
// #define POINTING_DEVICE_MOTION_PIN GP28

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_INVERT_Y

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE

#define HOLD_ON_OTHER_KEY_PRESS
